import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import BackToTop from "@/components/BackToTop";
const font = localFont({
  display: "swap",
  variable: "--font-sans",
  fallback: ["sans-serif"],
  preload: true,
  src: [
    {
      path: "./fonts/supreme-bold.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/supreme-black.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/supreme-book.woff2",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(font.variable, " bg-background text-text")}>
        <Header />
        <main>{children}</main>
        <Footer />
        <BackToTop />
      </body>
    </html>
  );
}
